---
name: sixteen_digit_project
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.14.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  dotted_line: ^3.0.0
  flutter_neumorphic:
    git:
      url: https://github.com/tsvillain/Flutter-Neumorphic.git
  flutter_staggered_grid_view: ^0.4.0
  introduction_screen: ^2.1.0
  flutter_spinkit: ^4.1.0
  image_picker: ^0.8.4+2
  shared_preferences: ^2.0.7
  page_transition: ^2.0.4
  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  flutter_animated_dialog: ^2.0.1
  intl: ^0.17.0
  pattern_formatter: ^2.0.0
  font_awesome_flutter: ^9.1.0
  device_preview: ^0.7.4
  fl_chart: ^0.40.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^0.22.0
  printing: ^5.5.0
  image: ^3.0.4
  dotted_border: ^2.0.0+1
  sleek_circular_slider: ^2.0.1
  animations: ^2.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/chat.png
    - assets/images/like.png
    - assets/images/prayer.png
    - assets/images/click21.png
    - assets/images/bank2.png
    - assets/images/ordercard2.png
    - assets/images/whatappemail.png
  fonts:
    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Light.ttf
          weight: 300
        - asset: assets/fonts/Oxygen-Regular.ttf
          weight: 400
        - asset: assets/fonts/Oxygen-Bold.ttf
          weight: 700
    - family: Mukta
      fonts:
        - asset: assets/fonts/Mukta-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Mukta-Light.ttf
          weight: 300
        - asset: assets/fonts/Mukta-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mukta-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mukta-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mukta-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mukta-ExtraBold.ttf
          weight: 800
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli-SemiBold.ttf
          weight: 600
    - family: Chaparral
      fonts:
        - asset: assets/fonts/ChaparralPro-Italic.otf
          weight: 100
        - asset: assets/fonts/ChaparralPro-Regular.otf
          weight: 400
        - asset: assets/fonts/ChaparralPro-Bold.otf
          weight: 700
        - asset: assets/fonts/ChaparralPro-BoldIt.otf
          weight: 900
    - family: Lucidi Sans Unicode
      fonts:
        - asset: assets/fonts/LSANS.TTF
          weight: 400
    - family: Calibri
      fonts:
        - asset: assets/fonts/calibri-regular.ttf
          weight: 400
    - family: Proximanova semibold
      fonts:
        - asset: assets/fonts/proximanova-semibold.otf
          weight: 600
